### PR TITLE
Improve process helper

### PR DESCRIPTION
**Pull request by asbjornu**
### Checklist

- [x] I have included examples or tests
- [ ] I have updated the change log
- [ ] I am listed in the CONTRIBUTORS file
- [x] I have cleaned up the commit history (use rebase and squash)

### Changes proposed in this pull request:

This PR wraps the setting of `Process.PriorityClass` in a `try`/`catch` so everything doesn't blow when trying to set it leads to [`System.ComponentModel.Win32Exception : Success`](https://travis-ci.org/GitTools/GitVersion/jobs/171288284#L2026) (as @cvpcs is having problems with in GitTools/GitVersion#1070) or [`System.InvalidOperationException : Cannot process request because the process (2989) has exited`](https://travis-ci.org/GitTools/GitVersion/jobs/166709203#L2278) (as @mkoertgen is having problems with in GitTools/GitVersion#720).

I think not being able to set the process' priority class does not warrant blowing up. I think not being able to set it (only failing on Mono/Mac it seems) will only lead to the process running at normal priority, which should be fine.

PS: Unfortunately, this PR also changes the EOL in some files, making it appear a much larger change than it actually is. The files had inconsistent line endings in the blob, making it very hard to work with on my Mac.

PPS: I'm not aware of any `CONTRIBUTORS` file or change log for this repository, which is why I haven't checked those two boxes above.

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
Too bad GitHub can't ignore non-relevant changes, but this looks good.

**Comment by asbjornu** [comment]
@GeertvanHorrik: Excellent, thanks! Now we just have to figure out how to get a new version of GitTools.Core published to NuGet. 🤔

**Comment by pascalberger** [comment]
@asbjornu @GeertvanHorrik Where are we regarding publishing a new version of the core package? I think it's really important to push this forward so that we can fix the build pipeline in GitVersion and can move on to accept PRs again

**Comment by gep13** [comment]
@pascalberger as per the discussion on Gitter, I think we are waiting to arrange a Skype call with @JakeGinnivan to walk through the current process, and to get it fully documented. If you can help in getting something arranged to facilitate that, I think it would be great!

**Comment by JakeGinnivan** [comment]
I put a PR up which explains the process on BitBucket. I have also done a release and am getting the builds green again :)

**Comment by gep13** [comment]
@JakeGinnivan sweet!

**Comment by asbjornu** [comment]
@JakeGinnivan: Fan-tas-tic! 😄  👍

**Pull request merged**
