### PR TITLE
Mono support

### PR DESCRIPTION
**Pull request by asbjornu**
## TODO

- [ ] Merge and pre-release GitTools/GitTools.Testing#2 on NuGet.
- [ ] Update to the above pre-release of GitTools.Testing.
- [x] Fix the [tests now failing](https://travis-ci.org/asbjornu/GitTools.Core#L2423) with `System.ArgumentNullException : Value cannot be null. Parameter name: source at System.Linq.Enumerable.ToArray[TSource] (IEnumerable`1 source)`
- [x] Fix [IO related failing tests](https://travis-ci.org/asbjornu/GitTools.Core/builds/124407128#L2412).
- [ ] Fix the [tests asserting the wrong temporary path](https://travis-ci.org/asbjornu/GitTools.Core/builds/124417372#L2425).
- [x] Fix [tests failing with `EntryPointNotFoundException` due to `SetErrorMode()` not being supported on Mono](https://travis-ci.org/asbjornu/GitTools.Core/builds/124417372#L2413).

## Overview

This PR adds a Travis build to ensure Linux/Mono compatibility and upgrades `LibGit2Sharp` to [version `0.23.0-pre20150419160303`](https://www.nuget.org/packages/LibGit2Sharp/0.23.0-pre20150419160303) so we get the fixes in libgit2/libgit2sharp#1298.

### GitTools.Testing

This PR depends on GitTools/GitTools.Testing#2 needs to be merged and released on NuGet, so that dependency can be updated.

When all of the above is figured out and fixed, it would be nice to have this merged and pre-released on NuGet, so I can go on to update GitVersion as well.

### CODE REVIEW

**Comment by asbjornu** [comment]
[Here's an example of how the tests now fail after updating LibGit2Sharp](https://travis-ci.org/asbjornu/GitTools.Core#L2423).

**Comment by asbjornu** [comment]
@JakeGinnivan The only thing left to fix now are [two tests failing on Travis (Linux)](https://travis-ci.org/asbjornu/GitTools.Core/builds/124425474#L2430) with something like this:

```
The provided expression
    should be
"/tmp/.git"
    but was
"/tmp/_4/.git"
```

On OS X it fails with something along these lines:

```
The provided expression
    should be
"/var/folders/_t/hkn5jvjd6blcf9tf8zv5cx8c0000gn/T/.git"
    but was
"/private/var/folders/_t/hkn5jvjd6blcf9tf8zv5cx8c0000gn/T/_5/.git"
```

Seems like [`Path.GetTempPath()` returning a symlink on OS X](https://stackoverflow.com/questions/11161867/mono-on-osx-returns-a-path-for-a-symlink-instead-of-the-real-folder-when-asking) is still a problem although mono/maccore#42 was merged 3 years ago.

Do you have any idea how we can make these temporary path tests a little more robust?

**Comment by dazinator** [comment]
Was just curious to know the reason behind using the temp directory.. why not force a directory to be specified, or default to the current working dir?

**Comment by asbjornu** [comment]
@dazinator I think using temporary paths for testing is reasonable. Hard coding a path would be hard to get right across different build environments, don't you agree? What I'm unsure of, is why the path is asserted in the first place. I don't understand the semantics of the assertion, so I'm unable to figure out another way to do it. Only @JakeGinnivan can help out there, I think.

**Comment by dazinator** [comment]
@asbjornu - perhaps i'm mistaken but I would have thought using a path relative to the test projects output directory would be fairly simple and keep everything under the developers working directory rather than accessing temp folder?

**Comment by asbjornu** [comment]
@dazinator Good point. If you have time to spare, do you think you could contribute some time to fixing this in [the few tests that are failing](https://travis-ci.org/asbjornu/GitTools.Core/builds/124425474#L2430)? You don't need to do a PR or anything; just fork the branch of this PR and push your stuff to your fork and I'll pull it into this PR after. That would be very much appreciated! ❤️

**Comment by dazinator** [comment]
@asbjornu - The tests seem to fail because they are a little brittle.

Basically in the failing test - this happens
```
GitTools.Tests.Git.GitRepositoryFactoryTests.PicksAnotherDirectoryNameWhenDynamicRepoFolderTaken
```

Basically this tries to establish a folder name in the temp directory for the repo, based on the repo name. If the folder name is already taken it recursively appends a number - `_N` to the path and checks again, until it finds a folder name that that is available to put the repo.

The test is not expecting this to happen.

I think it makes sense to switch away from using the temp dir as I have mentioned previously, but such a change would potentially impact GitVersion, so I have raised an issue over there to figure out what the consequence is if we swtiched: GitTools/GitVersion#822 

Once that's clarified, i'd be happy to contribute :)

**Comment by asbjornu** [comment]
@dazinator I've ignored the failing tests in #31, but you're more than welcome to submit a PR that un-ignores the tests and fixes the underlying problem! :+1:

**Pull request merged**
