### PR TITLE
Added NetStandard and Upgraded solution.

### LINKED ISSUE #40: Port to NETStandard
### Feature description

Port the solution NETStandard.
This will unlock ability to port GitVersionTask to .NETStandard.
This will unlock dotnet cli builds for projects that consume GitVersionTask

Here is the API Portability analysis: [ApiPortAnalysis.xlsx](https://github.com/GitTools/GitTools.Core/files/1109042/ApiPortAnalysis.xlsx)

### PR DESCRIPTION
**Pull request by dazinator**
Fixes #40 

### Changes proposed in this pull request:

- Converted from project per target, to a single vs2017 project that targets multiple: net40, net45 and NETStandard
- AppVeyor.yml changed to use vs2017 build image, and `msbuild /t:Pack` instead of `nuget pack`.
- Compiler directives to:
     - NETStandard build consumes `libgit2sharp.portable` package instead of normal one.
     - NETStandard build does not have `DumpGraph` API due to lack of `System.Diagnostics.Process` API's. `DumpGraph` is still available for the `net40` and `net45` targets.
     - NETStandard ~~uses a polyfill for the serializable attribute~~ depends on `System.Runtime.Serialization.Formatters` package for `[Serialzable]` attribute. (Had discovered using a polyfill is a bad idea due to netcore not supporting extern alias)
    - NETStandard - Serialization constructors where removed on exceptions as not required.
- JetBrains annotations package was upgraded.
- Tests project upgraded to new csproj format.
- Travis build updated to run under netcore on linux `trusty` distro, as opposed to mono. (Issue with NUnit adaptor when run under netcoreapp though means tests aren't executed)
- Temporary version of GitTools.Testing nuget package that I uploaded to nuget myself is being used. Because looks like latest build of GitTools.Testing hasn't incremented the nuget package version or published it, so I did this manually as I don't have access to fix the build for GitTools.Testing.

Open a command line and `dotnet build` to see the result.

### CODE REVIEW

**Comment by dazinator** [comment]
I'll need to make changes to the build process so that it builds with the latest msbuild. I plan to do this with the appveyor build - however I am not sure I can change the build just for a single branch - so as soon as I start adjusting it, it may break the builds for master, until this branch gets merged. If anyone has any suggestions to enable me to go about this in a better mannor I'm all ears!

**Comment by dazinator** [comment]
AppVeyor build now succedding! https://ci.appveyor.com/project/GitTools/gittools-core/build/1.2.1-PullRequest.42+33.build.122

**Comment by dazinator** [comment]
So exceptions don't need to be serializable in netcore because `netcore` doesn't support AppDomain's. However the other TfM's do. MS made the `[Serializable]` attribute available for `netstandard` libraries, just so that your code can still compile for those targeting multiple frameworks. The problem with creating your own polyfill for this attribute is that if multiple libraries each create a polyfill of this attribute, under .netcore - which doesn't support the ability to alias references, you end up with conflicts due to the attribute existing multiple times. Therefore it's best if any library needs the attribute, to all agree on using the attribute from here: https://www.nuget.org/packages/System.Runtime.Serialization.Formatters/

Or - wrap all uses of it in compiler directives so it's not used at all in netstandard / netcore builds.

**Comment by dazinator** [comment]
Ok now it's just the Travis build that needs fixing, and then I think this is ready for approval.

**Comment by dazinator** [comment]
I'm not familiar with Travis - can I ask that someone else help with fixing the travis build? Just need to get it building under latest msbuild (or dotnet cli which is what i attempted) but it seems the travis image doesn't support dotnet cli - it looks like a linux image..

**Comment by jarrodldavis** [comment]
You need to update the `.travis.yml` file to specify the Ubuntu distribution to build on (`trusty`). [Here's more information about .NET Core on Travis CI](https://docs.travis-ci.com/user/languages/csharp/#.NET-Core).

**Comment by dazinator** [comment]
@jarrodldavis - Thanks for that, I have switched to `trusty`. It now complains during the `dotnet build`:

```
mon.CurrentVersion.targets(1111,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/travis/build/GitTools/GitTools.Core/src/GitTools.Core.Tests/GitTools.Core.Tests.csproj]

```
I have specified `mono: latest` in the travis yaml. Any ideas how this needs to be resolved on travis?

**Comment by dazinator** [comment]
I'm going to convert the tests project to run under dotnet cli instead. (https://stackoverflow.com/questions/36578232/run-nunit-tests-in-dotnet-core)

**Comment by dazinator** [comment]
Ok I have run out of time and ideas trying to get the travis build to work now.
It seems when using `trusty` and the `dotnet cli` - you can't build for the full net framework - it always says the corresponding netframework reference assemblies are not installed (see travis build error message).

The AppVeyor build is fine. Not sure how to proceed - if this was my own personal project, I'd drop the travis build until this limitation could be overcome.

**Comment by dazinator** [comment]
Waiting on https://github.com/GitTools/GitTools.Testing/pull/6 to be merged, so can then get the tests on travis to run under netcoreapp.

**Comment by dazinator** [comment]
Running nunit tests under netcoreapp1.1 with the latest nunit adapator exhibits this: https://github.com/nunit/nunit3-vs-adapter/issues/325

Therefore I am multi-targeting the tests project for net46 and netcoreapp1.1 - so that in VS - the tests still show up in tests explorer under net46. AppVeyor can also run the tests under net46 if it wants to. Travis which will use netcoreapp1.1 won;t be able to get test results until this nunit adaptor issus is fixed.

**Comment by dazinator** [comment]
It seems many of the tests fail on linux under netcoreapp1.1 - is anyone able to investigate these tests? https://travis-ci.org/GitTools/GitTools.Core/builds/258618089?utm_source=github_status&utm_medium=notification

**Comment by dazinator** [comment]
WARNING: I am going to merge this tomorrow.

**Comment by dazinator** [comment]
Ok I am merging..

**Pull request merged**
