### PR TITLE
#18 Support GitLink

### PR DESCRIPTION
**Pull request by GeertvanHorrik**

### CODE REVIEW

**Comment by gep13** [comment]
So this is something that I never really understood was required.  So in order for GitLink to function, you need to run the exe against the source code, is that correct?

I have recently submitted PR's into Cake to get native support for GitVersion, GitReleaseNotes, and GitReleaseManager in their tooling, you can find it here:

http://cakebuild.net/dsl

Does it make sense to do the same for GitLink?

**Comment by GeertvanHorrik** [comment]
It only makes sense if you want to be able to step through the cakebuild code. So GitLink is really useful when you want to use "step into" for other libs. For example when I am developing GitReleaseNotes, I want to be able to step into GitTools.Core and GitTools.IssueTrackers.

**Comment by gep13** [comment]
Cake is a build system, so wasn't planning on using GitLink directly, but rather, providing the ability for people using Cake as their Build System, to then call GitLink on their project.

Something like:

```
Task("Run-GitLink")
    .Does(() =>
{
    GitLink(new GitLinkSettings {
        UserName = "https://github.com/gittools/gittools.core",
        Branch = EnvironmentVariable("APPVEYOR_REPO_BRANCH"),
        Source = EnvironmentVariable("APPVEYOR_REPO_COMMIT"),
        FileName = "src/GitTools.Core.sln"
    });
});
```
In the same way that you can call GitVersion currently: http://cakebuild.net/api/cake.common.tools.gitversion/84dbc5a7/73d63de7

**Comment by GeertvanHorrik** [comment]
That is really nice. But don't use that username ;-)

**Comment by GeertvanHorrik** [comment]
But to explain:

1. Run GitLink against soruce files
2. Include pdbs in nuspec

Now I think about it, I might have forgotten 2

**Comment by gep13** [comment]
>@GeertvanHorrik said...
That is really nice. But don't use that username ;-)

I was guessing at what the `-u` parameter was.

**Comment by GeertvanHorrik** [comment]
It stands for url. It doesn't make sense to have authentication (it's not supported by source servers (or the clients)).

**Comment by gep13** [comment]
Yip, that makes perfect sense, in which case, I think GitLink would be a nice addition into the Cake Common Tooling, and can sit beside GitVersion, GitReleaseNotes, and GitReleaseManager :smile:

**Comment by gep13** [comment]
>@GeertvanHorrik said...
It stands for url. It doesn't make sense to have authentication (it's not supported by source servers (or the clients)).

Ah, that makes sense :+1:

**Pull request merged**
